### PR TITLE
feat(api): add summary to package findings

### PR DESCRIPTION
**Pull request by ramizpolic**
## Description

Adds summary field to findings. Registers a new processor for findings to calculate vulnerability severity count for applicable finding types (i.e. only for packages).

Closes https://github.com/openclarity/vmclarity/issues/1040

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/openclarity/vmclarity/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [x] New code contribution is covered by automated tests
- [x] All new and existing tests pass

### CODE REVIEW

**Comment by ramizpolic** [comment]
UI changes are left to be resolved

**Comment by ramizpolic** [comment]
UI changes have also been added. The package findings page now looks like this

### Packages table
image

### Package details
image

There is a bug left to be fixed when we need to redirect from package details page on click to "Package Vulnerabilities" to related package vulnerabilities table view. @gallotamas is looking into this

**Review by paralta — APPROVED** [review]
LGTM 👍 the backend part looks good to me

**Review by adamtagscherer — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
